<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use ShopBundle\Entity\Product;
use Doctrine\ORM\Mapping;
use Doctrine\ORM\NoResultException;
use ShopBundle\Entity\ProductImage;


/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
	/**
	 * @var EntityManagerInterface $em
	 */
	private $em;

	/**
	 * UserRepository constructor.
	 *
	 * @param EntityManagerInterface $em
	 */
	public function __construct(EntityManagerInterface $em ) {
		parent::__construct( $em, new Mapping\ClassMetadata(Product::class) );
		$this->em = $em;
	}

	/**
	 * @param Product $product
	 */
	public function createNewProduct(Product $product){
		$em = $this->em;
		$em->persist($product);
		$em->flush();
	}

	/**
	 * @return mixed|string
	 */
	public function findAllProducts(){
		$em = $this->em;
		$query = $em->createQueryBuilder()
			->select('pt')
			->from('ShopBundle:Product','pt')
			->join('pt.category','cat')
			->join('pt.promotion','pr')
			->orderBy('pt.dateCreated','DESC')
			->getQuery();
		try{
			return $query->getResult();
		} catch (NoResultException $e){
			return $e->getMessage();
		}

	}
}
