<?php

namespace AppBundle\Repository;
use AppBundle\Entity\UserAddress;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Mapping;

/**
 * UserAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAddressRepository extends EntityRepository
{

	/**
	 * @var EntityManagerInterface $em
	 */
	private $em;

	public function __construct(EntityManagerInterface $em) {
		parent::__construct( $em, new Mapping\ClassMetadata(UserAddress::class) );

		$this->em = $em;
	}

	public function findAddressJoinUser($id){
		$em = $this->getEntityManager();
		$query = $em->createQuery("SELECT adr, u 
									  	FROM AppBundle:UserAddress adr 
									  	JOIN adr.user u 
									  	WHERE u.id = :id")
		;
		$query->setParameter('id',$id);
		try{
			return $query->getSingleResult();
		}   catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
