shop:
    resource: "@ShopBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"

personal_cart:
    path: /products_summary
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    ShopBundle:order:personal_cart.html.twig
